# Generated by Django 6.0.5 on 2026-05-18 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Unsplash ya koi bhi image link dalein', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='package_name',
            field=models.CharField(default='Full Body Package', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default=999999, max_length=200),
            preserve_default=False,
        ),
    ]
