# Generated by Django 6.0.5 on 2026-05-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_service_category_remove_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+91 ', max_length=15)),
                ('whatsapp_number', models.CharField(default='+91 ', max_length=15)),
                ('email', models.EmailField(default='info@bhawnabeautystudio.com', max_length=254)),
                ('address', models.TextField(default='Kanpur, Uttar Pradesh')),
                ('google_map_link', models.URLField(blank=True, help_text='Google Maps ka embed/share link dalein', max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Salon Contact Info',
                'verbose_name_plural': 'Salon Contact Info',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Studio Service', 'verbose_name_plural': 'Studio Services'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.category', verbose_name='Select Category'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Apni gallery/computer se image upload karein', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='package_name',
            field=models.CharField(default='Full Body Package', max_length=200, verbose_name='Package Details'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Price (₹)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Service Name'),
        ),
    ]
